"""users jwt

Revision ID: d8153e7da443
Revises: 27ce37dc6a39
Create Date: 2020-09-25 11:34:37.480983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8153e7da443'
down_revision = '27ce37dc6a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', mysql.DATETIME(), nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=True)
    # ### end Alembic commands ###
